#!/usr/bin/env ruby
# frozen_string_literals: true
require 'getoptlong'
require 'open3'

#######################################################################
# Usage/help and examples:

def usage
<<-END
Usage: #{$0} [OPTIONS...] SRC... DST -- [FIND OPTIONS...] -- [SYNC OPTIONS...]

OPTIONS:
  -f, --finders N    - Max number of rsync find processes running at the same
                       time. Each one processes one SRC path at a time. If not
                       specified, defaults to the number of SRC paths
  -s, --syncers 1    - Nr. of respawning rsync sync/copy processes, per finder
  -b, --batchsize 5  - Number of files to queue before starting a sync
  -q, --queuesize 50 - Max number of paths to queue for sync. If not specified,
                       defaults to batchsize * 10. Rsync find processes get
                       automatically paused when their queue goes above this
                       limit and are resumed when queue falls below threshold
  -t, --timeout 5.0  - After timeout seconds, run rsync sync/copy process even
                       if batch wasn't full
  -d, --delete       - Delete files from DST which don't exist in SRC (same
                       as rsync option --delete)
  -R, --relative     - Sync SRC paths with their full names, instead of just
                       the last part (same as rsync option --relative)

  -r, --rsync rsync  - Name (and/or path) of rsync binary

  -v, --verbose      - Enable rsyncnow and rsync verbose mode
  -h, --help         - Show help and exit
  -e, --examples     - Show examples and exit

SRC, DST:
  Rsync source and destination as usual (including the "/" magic)

FIND OPTIONS:
  If specified, overrides all default cmdline options for rsync find processes.
  Default value: -ae=ssh
    NOTE: options `--dry-run --no-relative --out-format='%i %n'` are always
    added automatically. To use rsync option -R, use option -R of rsyncnow.

SYNC OPTIONS:
  If specified, overrides all default cmdline options for rsync sync processes.
  Default value: -lptgoD0e=ssh --files-from=-
    NOTE: options `--from0 --files-from=-` are always added automatically.
    NOTE: options -lptgoD are used explicitly instead just specifying -a
    because -a also includes option -r which should not be present. Recursion
    is controlled via FIND OPTIONS (where it is enabled/implied by -a)
END
end

def examples
<<-END
Usage: #{$0} [OPTIONS...] SRC... DST -- [FIND OPTIONS...] -- [SYNC OPTIONS...]

EXAMPLES:

# Most basic example:
# (implies finding files to sync with rsync options -ae=ssh,
# and syncing the actual files with rsync options -lptgoD0e=ssh --files-from=-)
rsyncnow -v /source/dir /target/dir

# Finding files to sync based on file size only, without full checksum:
rsyncnow -v /source/dir /target/dir -- -ae=ssh --size-only
END
end

#######################################################################
# Parse config:

$C= {
  finders: nil,
  syncers: 1,
  batchsize: 5,
  queuesize: nil,
  timeout: 5.0,
  rsync: 'rsync',
  delete: false,
  relative: false,
  verbose: false,
  sources: [],
  find_options: %w/-ae=ssh/,
  # Options that are always added to rsync find processes
  find_options_always: ['--dry-run', '--no-relative', '--out-format=%i %n'],
  sync_options: %w/-lptgoD0e=ssh --files-from=-/,
  # Runtime variables (mostly accessed while holding a mutex):
  runtime: {
    status: 0,
    synced: false,
    changed: false,
  }
}

$mutex= Mutex.new
$first= Mutex.new

# An exception in any thread ends the program, as otherwise the other
# threads could be left waiting for that thread forever
Thread.abort_on_exception= true

# Process IDs of rsync processes which are currently running
$children= {}

# If rsyncnow exits while rsync processes are still running (e.g. because it
# was interrupted), they are terminated. Finders which are paused need to
# be resumed for that, and would otherwise stay paused forever.
$pid= Process.pid
at_exit {
  if Process.pid== $pid
    $children.keys.each {|pid|
      %w/CONT TERM/.each {|signal|
        begin
          Process.kill signal, pid
        rescue Errno::ESRCH
        end
      }
    }
  end
}
%w/INT TERM HUP/.each {|signal|
  trap(signal) { exit 128+ Signal.list[signal] }
}

# Arguments are treated as binary data because paths can contain anything
ARGV.map! &:b

# Parse program options (note: does not include rsync-specific options)
opts= GetoptLong.new(
  [ '--finders', '-f', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--syncers', '-s', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--batchsize', '-b', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--queuesize', '-q', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--timeout', '-t', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--delete', '-d', GetoptLong::NO_ARGUMENT ],
  [ '--relative', '-R', GetoptLong::NO_ARGUMENT ],
  [ '--rsync', '-r', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--verbose', '-v', GetoptLong::NO_ARGUMENT ],
  [ '--help', '-h', GetoptLong::NO_ARGUMENT ],
  [ '--examples', '-e', GetoptLong::NO_ARGUMENT ],
)
opts.ordering= 2

begin
  opts.each do |opt, arg|
    case opt
    when '--finders', '--syncers', '--batchsize', '--queuesize'
      $C[opt[2..].to_sym]= arg.to_i
    when '--timeout'
      $C[opt[2..].to_sym]= arg.to_f
    when '--rsync'
      $C[:rsync]= arg
    when '--delete'
      $C[:delete]= true
    when '--relative'
      $C[:relative]= true
    when '--verbose'
      $C[:verbose]= true
    when '--help'
        puts usage
        exit 0
    when '--examples'
        puts examples
        exit 0
    when ''
      $C[:sources].push arg
    end
  end
rescue GetoptLong::Error
  # (GetoptLong has already printed the error message)
  abort "Run #{$0} --help for the list of options"
end

# See if there are any rsync find options provided
if ARGV.size> 0
  if i = ARGV.index('--')
    ARGV.delete_at i
  else
    i = ARGV.size
  end
  # (An empty list, as in "-- -- SYNC OPTIONS", doesn't override the default)
  options = ARGV.shift i
  $C[:find_options] = options unless options.empty?
end

# See if there are any rsync sync options provided
if ARGV.size> 0
  if i = ARGV.index('--')
    ARGV.delete_at i
  else
    i = ARGV.size
  end
  options = ARGV.shift i
  $C[:sync_options] = options unless options.empty?
end

#######################################################################
# Do final option adjustments:

# Last path is always destination, and all others before it are sources
$C[:destination]= $C[:sources].pop

if $C[:sources].empty?
  abort usage.lines.first+ "Run #{$0} --help for more information"
end

# Queue size, if unspecified, defaults to 10 x batchsize
$C[:queuesize]||= $C[:batchsize]* 10

# Each finder processes one source at a time, so there is no use for more
# finders than sources. That is also the default number of finders.
if !$C[:finders] or $C[:finders]> $C[:sources].size
  $C[:finders]= $C[:sources].size
end

%i/finders syncers batchsize queuesize timeout/.each do |name|
  abort "Value of option --#{name} must be greater than 0" unless $C[name]> 0
end

unless system $C[:rsync], '--version', out: File::NULL, err: File::NULL
  abort "Can't run rsync (#{$C[:rsync]})"
end

# Syncers always read the paths to sync from STDIN, separated with "\0"
unless $C[:sync_options].any? {|a| a.start_with? '--files-from' }
  $C[:sync_options].push '--files-from=-'
end
$C[:sync_options].push '--from0'

if $C[:verbose]
  $C[:sync_options].unshift '-v'
end

if $C[:relative]
  $C[:find_options_always].map! {|a| a== '--no-relative' ? '--relative' : a }
end

if $C[:delete]
  $C[:find_options_always].push '--delete'
  # Files in SRC must be able to replace non-empty directories in DST
  $C[:sync_options].push '--force'
  # Options for rsync processes which delete files. Those processes run
  # with the same SRC and DST as finders. Filter rules for the paths to
  # delete are read from STDIN, and all other paths are excluded. Also,
  # no files are created or updated, so that nothing is done except deleting.
  $C[:delete_options]= $C[:sync_options].reject {|a| a.start_with? '--files-from' }+
    ['-r', '--delete', '--from0', '--filter=. -', '--exclude=*', '--existing', '--ignore-existing']
  $C[:delete_options].push '--relative' if $C[:relative]
end

# Options for rsync process which syncs the attributes of source directory
# itself (and nothing else) if its contents are synced, as with "SRC/"
$C[:top_options]= $C[:sync_options].reject {|a| a.start_with? '--files-from' }+
  ['--dirs', '--exclude=*']
$C[:top_options].push '--relative' if $C[:relative]

def v msg; $C[:verbose] and puts msg end

#######################################################################
# Define helper functions:

RSYNC_HOST= %r{(?:[^/:@]+@)?(?:\[[^\]]+\]|[^/:]+)}

# Splits rsync source into the directory that the paths printed by finder
# are relative to, and the name of the item to sync in that directory.
# Name is nil if source's contents are synced instead (as with "dir/").
# Also returns the prefix which needs to be added to paths given to syncer.
#
# In relative mode (option -R) the paths are relative to the part of source
# before "/./" if it contains that, or otherwise to the root directory or
# the current directory. Name is then the rest of source.
def split_source source
  daemon= false
  prefix, path= case source
    when %r{\A(rsync://[^/]+/[^/]*)(.*)\z}m, %r{\A(#{RSYNC_HOST}::[^/]*)(.*)\z}m
      # Rsync daemon; module without a path is the same as "module/"
      daemon= true
      [$1, $2.empty? ? '/' : $2]
    when %r{\A(#{RSYNC_HOST}:)(.*)\z}m
      # Remote shell; paths are relative to home directory. Leading "~/" is
      # removed because rsync doesn't expand it when --files-from is used
      [$1, $2.sub(%r{\A~(/|\z)}, '')]
    else
      ['', source]
  end
  path= '.' if path.empty?

  if $C[:relative]
    root, marker, name= path.partition '/./'
    if marker.empty?
      root, name= (path.start_with?('/') ? '/' : './'), path
    else
      root+= '/'
    end
    name= name.sub(%r{\A(\./|/)+}, '').chomp '/'
    name= '' if name== '.'
  else
    dir, _, name= path.rpartition '/'
    if name.empty?
      root, name= path, nil
    elsif name== '.' or name== '..'
      root, name= path+ '/', nil
    else
      root= dir.empty? ? './' : dir+ '/'
    end
  end

  if daemon and root!= '/'
    # Rsync daemon doesn't find the files from --files-from if source is a
    # directory inside of a module. So module is used as source, and the
    # directory is added to paths (where "/./" marks the part to ignore)
    [prefix+ '/', name&.b, (root[1..]+ './').b]
  else
    [prefix+ root, name&.b, '']
  end
end

# Returns DST for syncer. It always needs to be treated as a directory,
# even when it doesn't exist yet and a batch contains only one file.
def dir_dest dest
  if dest.end_with? '/'
    dest
  elsif dest=~ %r{\A#{RSYNC_HOST}:\z}
    dest+ './'
  else
    dest+ '/'
  end
end

# Parses a line printed by finder (in format "%i %n") and returns item
# type and path to sync. Type is "*" if the path is to be deleted from DST.
# Returns nil for all other lines (messages etc.)
def parse_line l
  l= l.b.chomp "\n"
  return unless l=~ /\A(?:[<>ch.]([fdLDS]).{9}|(\*)deleting  ) (.+)\z/mn
  # Items without any changes are printed if finder is more verbose (-ii)
  return if l.start_with? '.' and l[2, 9].strip.empty?
  type= $1|| $2
  # Undo rsync's escaping of unprintable characters (e.g. newline is \#012)
  path= $3.gsub(/\\#(\d{3})/n) { $1.oct.chr }

  # In relative mode, absolute local paths are printed with the leading "/"
  if $C[:relative]
    path= path.sub %r{\A/}n, ''
    return if path.empty?
  end

  # Paths to delete are returned as they are (directories end with "/")
  return [type, path] if type== '*'

  # Source directory itself can't be synced without also listing its contents,
  # so no path is returned. (Its attributes are synced separately at the end.)
  return [type] if path== './'

  # Same goes for other directories if they are specified with a trailing "/"
  [type, path.chomp('/')]
end

# Returns rsync filter rules for deleting the path from DST, separated with
# "\0". Parent directories of the path need to be sent by the sending side
# (rule "S") so that rsync looks into them in DST, and the path itself
# needs to be included (rule "+"; with its contents if it is a directory).
# As everything else is excluded, nothing else can get deleted.
def delete_rules path
  # Wildcards need to be escaped. But backslash is a regular character
  # in patterns which don't contain any wildcards.
  pattern= lambda {|path, suffix|
    path= path.gsub(/[\\*?\[]/n) { '\\'+ $& } if (path+ suffix)=~ /[*?\[]/n
    '/'+ path+ suffix
  }

  dirs= path.chomp('/').split '/'
  dirs.pop
  rules= dirs.each_index.map {|i| 'S '+ pattern.(dirs[0..i].join('/'), '/') }
  rules<< '+ '+ (path.end_with?('/') ? pattern.(path, '***') : pattern.(path, ''))
  rules.join "\0"
end

# Remembers exit status of the first rsync process that failed. That
# value is then used as exit status of rsyncnow.
def check status
  return if status.success?
  $mutex.synchronize {
    $C[:runtime][:status]= status.exitstatus|| 1 if $C[:runtime][:status]== 0
  }
end

# Runs rsync process and waits for it to finish
def run cmdline
  pid= spawn *cmdline
  $children[pid]= true
  Process.wait pid
  $children.delete pid
  check $?
end

# Sends a signal to finder process. Does nothing if finder has already
# exited, which is normal (its output may still be waiting to be read).
def signal_finder thread, signal
  Process.kill signal, thread.pid if thread.alive?
rescue Errno::ESRCH
end

# Runs the block. The first run is done alone, because rsync may then need
# to create DST, and multiple rsync processes can't do that at the same time.
def first_alone
  if $C[:runtime][:synced]
    yield
  else
    $first.synchronize {
      yield
      $C[:runtime][:synced]= true
    }
  end
end

#######################################################################
# Define worker classes:

class Finder
  def initialize cmd, args, sources, dest
    # Sources are taken from the queue which is shared by all finders
    while source= sources.pop
      queue= Queue.new
      queues= [queue]
      threads= []
      root, name, prefix= split_source source
      cmdline= [cmd, args, $C[:find_options_always], source, dest].flatten
      v "Starting finder: %s" % [cmdline]
      $C[:syncers].times do |i|
        threads<< Thread.new { Syncer.new queue, $C[:rsync], $C[:sync_options], root, dir_dest(dest) }
      end
      if $C[:delete]
        # Paths to delete have a separate queue, and a syncer which deletes them
        queues<< deletes= Queue.new
        threads<< Thread.new { Syncer.new deletes, $C[:rsync], $C[:delete_options], source, dest }
      end

      Open3.popen2(*cmdline) {|i,o,t|
        $children[t.pid]= true
        o.each_line do |l|
          type, path= parse_line l

          # Anything found by finder means that DST is going to change
          $C[:runtime][:changed]= true if type

          if path
            if type== '*'
              deletes<< delete_rules(path) if deletes
            elsif type!= 'd' and path== name and $C[:sources].size== 1 and !$C[:relative]
              # A single file is synced by running rsync on it directly,
              # because in that case DST can also be the new name of the file
              direct= [cmd, $C[:sync_options].reject {|a| a.start_with? '--files-from' }, source, dest].flatten
              v "Running syncer for a single file: %s" % [direct]
              run direct
            else
              # Rsync ignores the paths which start with "#" or ";" (as comments)
              path= './'+ path if prefix.empty? and path=~ /\A[#;]/n
              queue<< prefix+ path
            end
          end

          if queues.any? {|q| q.size> $C[:queuesize] }
            signal_finder t, 'STOP'
            v 'Queue contains %d files, pausing finder while queue is being processed' % queues.sum(&:size)
            while queues.any? {|q| q.size> $C[:queuesize] }
              sleep $C[:timeout]
            end
            signal_finder t, 'CONT'
          end
        end
        $children.delete t.pid
        check t.value
      }

      # Closing the queue tells syncers that there will be no more paths
      queues.each &:close
      threads.each &:join
    end
  end
end

class Syncer
  # Returns the next path from the queue. Returns nil if there is none after
  # waiting for timeout seconds, or as soon as queue is closed and empty.
  # (Timeout::timeout isn't used because a path could get lost in a timeout)
  def pop queue
    time= Time.now
    begin
      queue.pop true
    rescue ThreadError
      return if (queue.closed? and queue.empty?) or Time.now- time>= $C[:timeout]
      sleep 0.01
      retry
    end
  end

  def initialize queue, cmd, args, source, dest
    cmdline= [cmd, args, source, dest].flatten
    v "Starting syncer: %s" % [cmdline]

    done= false
    until done
      list= []
      $C[:batchsize].times do |i|
        if path= pop(queue)
          list.push path
        else
          # If queue is closed and empty, there is no need to wait for more paths
          done= (queue.closed? and queue.empty?)
          if list.size> 0
            v 'Finder %s for %s; running syncer with %d out of %d paths' % [done ? 'done' : 'timeout reached', source, list.size, $C[:batchsize]]
          end
          break
        end
      end

      if list.size> 0
        if list.size== $C[:batchsize]
          v 'Finder batch size reached for %s; running syncer with a batch of %d paths' % [source, $C[:batchsize]]
        end
        first_alone do
          read_io, write_io= IO.pipe
          child= fork do
            write_io.close
            STDIN.reopen read_io
            exec *cmdline
          end
          $children[child]= true
          read_io.close
          begin
            write_io.write list.join "\0"
            write_io.close
          rescue Errno::EPIPE
            # Rsync has exited without reading the paths; its exit status tells why
          end
          Process.wait child
          $children.delete child
          check $?
        end
      end
    end

    #v 'No more finders running and no more paths queued for %s; closing' % [source]
  end
end


#######################################################################
# Run the thing:

v "Config: #{$C}"

# Finders work independently, and each one would delete from DST the files
# which don't exist in its SRC. So they must not be syncing into the same
# directory, which is the case if contents of a directory are synced ("SRC/").
if $C[:delete] and $C[:sources].size> 1
  sources= $C[:sources].map {|source| split_source source }
  if $C[:relative]
    # In relative mode that is only a problem if sources are relative to
    # different directories, and one is synced into the directory of another
    conflict= sources.combination(2).any? {|(root1, name1), (root2, name2)|
      root1!= root2 and (name1.empty? or name2.empty? or
        (name1+ '/').start_with?(name2+ '/') or (name2+ '/').start_with?(name1+ '/'))
    }
  else
    names= sources.map {|root, name| name }
    conflict= (names.include? nil or names.uniq!)
  end
  if conflict
    abort 'Option --delete can be used with multiple SRC paths only if they are synced into different directories in DST'+
      ($C[:relative] ? '' : ' (which is not the case if SRC ends with "/")')
  end
end

sources= Queue.new
$C[:sources].each {|source| sources<< source }
sources.close

threads= []
$C[:finders].times do |i|
  threads<< Thread.new { Finder.new $C[:rsync], $C[:find_options], sources, $C[:destination] }
end
threads.each &:join

# If contents of a directory are synced (as with "SRC/"), DST gets the
# attributes of that directory. They can only be synced at the end, because
# modification time of DST changes while files are synced into it. If there
# are multiple such sources, rsync uses the attributes of the first one.
top= $C[:sources].find {|source|
  name= split_source(source)[1]
  name.nil? or name.empty?
}
if top and $C[:runtime][:changed]
  cmdline= [$C[:rsync], $C[:top_options], top, $C[:destination]].flatten
  v "Syncing attributes of %s: %s" % [top, cmdline]
  run cmdline
end

exit $C[:runtime][:status]
