#!/usr/bin/env ruby
# frozen_string_literals: true
require 'getoptlong'
require 'open3'

#######################################################################
# Usage/help and examples:

def usage
<<-END
Usage: #{$0} [OPTIONS...] SRC... DST -- [FIND OPTIONS...] -- [SYNC OPTIONS...]

OPTIONS:
  -f, --finders N    - Max number of rsync find processes running at the same
                       time. Each one processes one SRC path at a time. If not
                       specified, defaults to the number of SRC paths
  -s, --syncers 1    - Nr. of respawning rsync sync/copy processes, per finder
  -b, --batchsize 5  - Number of files to queue before starting a sync
  -q, --queuesize 50 - Max number of paths to queue for sync. If not specified,
                       defaults to batchsize * 10. Rsync find processes get
                       automatically paused when their queue goes above this
                       limit and are resumed when queue falls below threshold
  -t, --timeout 5.0  - After timeout seconds, run rsync sync/copy process even
                       if batch wasn't full

  -r, --rsync rsync  - Name (and/or path) of rsync binary

  -v, --verbose      - Enable rsyncnow and rsync verbose mode
  -h, --help         - Show help and exit
  -e, --examples     - Show examples and exit

SRC, DST:
  Rsync source and destination as usual (including the "/" magic)

FIND OPTIONS:
  If specified, overrides all default cmdline options for rsync find processes.
  Default value: -ae=ssh
    NOTE: options `--dry-run --no-relative --out-format='%i %n'` are always
    added automatically. This also means that option -R can not be used.

SYNC OPTIONS:
  If specified, overrides all default cmdline options for rsync sync processes.
  If you use this, options `-0 --files-from=-` must always remain present.
  Default value: -lptgoD0e=ssh --files-from=-
    NOTE: options -lptgoD are used explicitly instead just specifying -a
    because -a also includes option -r which should not be present. Recursion
    is controlled via FIND OPTIONS (where it is enabled/implied by -a)
END
end

def examples
<<-END
Usage: #{$0} [OPTIONS...] SRC... DST -- [FIND OPTIONS...] -- [SYNC OPTIONS...]

EXAMPLES:

# Most basic example:
# (implies finding files to sync with rsync options -ae=ssh,
# and syncing the actual files with rsync options -lptgoD0e=ssh --files-from=-)
rsyncnow -v /source/dir /target/dir

# Finding files to sync based on file size only, without full checksum:
rsyncnow -v /source/dir /target/dir -- -ae=ssh --size-only
END
end

#######################################################################
# Parse config:

$C= {
  finders: nil,
  syncers: 1,
  batchsize: 5,
  queuesize: nil,
  timeout: 5.0,
  rsync: 'rsync',
  verbose: false,
  sources: [],
  find_options: %w/-ae=ssh/,
  # Options that are always added to rsync find processes
  find_options_always: ['--dry-run', '--no-relative', '--out-format=%i %n'],
  sync_options: %w/-lptgoD0e=ssh --files-from=-/,
  # Runtime variables (mostly accessed while holding a mutex):
  runtime: {
    status: 0,
    synced: false,
  }
}

$mutex= Mutex.new
$first= Mutex.new

# Arguments are treated as binary data because paths can contain anything
ARGV.map! &:b

# Parse program options (note: does not include rsync-specific options)
opts= GetoptLong.new(
  [ '--finders', '-f', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--syncers', '-s', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--batchsize', '-b', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--queuesize', '-q', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--timeout', '-t', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--rsync', '-r', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--verbose', '-v', GetoptLong::NO_ARGUMENT ],
  [ '--help', '-h', GetoptLong::NO_ARGUMENT ],
  [ '--examples', '-e', GetoptLong::NO_ARGUMENT ],
)
opts.ordering= 2

opts.each do |opt, arg|
  case opt
  when '--finders', '--syncers', '--batchsize', '--queuesize'
    $C[opt[2..].to_sym]= arg.to_i
  when '--timeout'
    $C[opt[2..].to_sym]= arg.to_f
  when '--rsync'
    $C[:rsync]= arg
  when '--verbose'
    $C[:verbose]= true
  when '--help'
      puts usage
      exit 0
  when '--examples'
      puts examples
      exit 0
  when ''
    $C[:sources].push arg
  end
end

# See if there are any rsync find options provided
if ARGV.size> 0
  if i = ARGV.index('--')
    ARGV.delete_at i
  else
    i = ARGV.size
  end
  $C[:find_options] = ARGV.shift i
end

# See if there are any rsync sync options provided
if ARGV.size> 0
  if i = ARGV.index('--')
    ARGV.delete_at i
  else
    i = ARGV.size
  end
  $C[:sync_options] = ARGV.shift i
end

#######################################################################
# Do final option adjustments:

# Last path is always destination, and all others before it are sources
$C[:destination]= $C[:sources].pop

# Queue size, if unspecified, defaults to 10 x batchsize
$C[:queuesize]||= $C[:batchsize]* 10

# Each finder processes one source at a time, so there is no use for more
# finders than sources. That is also the default number of finders.
if !$C[:finders] or $C[:finders]> $C[:sources].size
  $C[:finders]= $C[:sources].size
end
$C[:finders]= 1 if $C[:finders]< 1

if $C[:verbose]
  $C[:sync_options].unshift '-v'
end

def v msg; $C[:verbose] and puts msg end

#######################################################################
# Define helper functions:

RSYNC_HOST= %r{(?:[^/:@]+@)?(?:\[[^\]]+\]|[^/:]+)}

# Splits rsync source into the directory that the paths printed by finder
# are relative to, and the name of the item to sync in that directory.
# Name is nil if source's contents are synced instead (as with "dir/").
# Also returns the prefix which needs to be added to paths given to syncer.
def split_source source
  daemon= false
  prefix, path= case source
    when %r{\A(rsync://[^/]+/[^/]*)(.*)\z}m, %r{\A(#{RSYNC_HOST}::[^/]*)(.*)\z}m
      # Rsync daemon; module without a path is the same as "module/"
      daemon= true
      [$1, $2.empty? ? '/' : $2]
    when %r{\A(#{RSYNC_HOST}:)(.*)\z}m
      # Remote shell; paths are relative to home directory. Leading "~/" is
      # removed because rsync doesn't expand it when --files-from is used
      [$1, $2.sub(%r{\A~(/|\z)}, '')]
    else
      ['', source]
  end
  path= '.' if path.empty?

  dir, _, name= path.rpartition '/'
  if name.empty?
    root, name= path, nil
  elsif name== '.' or name== '..'
    root, name= path+ '/', nil
  else
    root= dir.empty? ? './' : dir+ '/'
  end

  if daemon and root!= '/'
    # Rsync daemon doesn't find the files from --files-from if source is a
    # directory inside of a module. So module is used as source, and the
    # directory is added to paths (where "/./" marks the part to ignore)
    [prefix+ '/', name&.b, (root[1..]+ './').b]
  else
    [prefix+ root, name&.b, '']
  end
end

# Returns DST for syncer. It always needs to be treated as a directory,
# even when it doesn't exist yet and a batch contains only one file.
def dir_dest dest
  if dest.end_with? '/'
    dest
  elsif dest=~ %r{\A#{RSYNC_HOST}:\z}
    dest+ './'
  else
    dest+ '/'
  end
end

# Parses a line printed by finder (in format "%i %n") and returns item
# type and path to sync. Returns nil for all other lines (messages etc.)
def parse_line l
  l= l.b.chomp "\n"
  return unless l=~ /\A[<>ch.]([fdLDS]).{9} (.+)\z/mn
  type= $1
  # Undo rsync's escaping of unprintable characters (e.g. newline is \#012)
  path= $2.gsub(/\\#(\d{3})/n) { $1.oct.chr }

  # Source directory itself can't be synced without also listing its contents
  return if path== './'

  # Same goes for other directories if they are specified with a trailing "/"
  [type, path.chomp('/')]
end

# Remembers exit status of the first rsync process that failed. That
# value is then used as exit status of rsyncnow.
def check status
  return if status.success?
  $mutex.synchronize {
    $C[:runtime][:status]= status.exitstatus|| 1 if $C[:runtime][:status]== 0
  }
end

# Sends a signal to finder process. Does nothing if finder has already
# exited, which is normal (its output may still be waiting to be read).
def signal_finder thread, signal
  Process.kill signal, thread.pid if thread.alive?
rescue Errno::ESRCH
end

# Runs the block. The first run is done alone, because rsync may then need
# to create DST, and multiple rsync processes can't do that at the same time.
def first_alone
  if $C[:runtime][:synced]
    yield
  else
    $first.synchronize {
      yield
      $C[:runtime][:synced]= true
    }
  end
end

#######################################################################
# Define worker classes:

class Finder
  def initialize cmd, args, sources, dest
    # Sources are taken from the queue which is shared by all finders
    while source= sources.pop
      queue= Queue.new
      threads= []
      root, name, prefix= split_source source
      cmdline= [cmd, args, $C[:find_options_always], source, dest].flatten
      v "Starting finder: %s" % [cmdline]
      $C[:syncers].times do |i|
        threads<< Thread.new { Syncer.new queue, $C[:rsync], $C[:sync_options], root, dir_dest(dest) }
      end

      Open3.popen2(*cmdline) {|i,o,t|
        o.each_line do |l|
          type, path= parse_line l

          if path
            if type!= 'd' and path== name and $C[:sources].size== 1
              # A single file is synced by running rsync on it directly,
              # because in that case DST can also be the new name of the file
              direct= [cmd, $C[:sync_options].reject {|a| a.start_with? '--files-from' }, source, dest].flatten
              v "Running syncer for a single file: %s" % [direct]
              system *direct
              check $?
            else
              queue<< prefix+ path
            end
          end

          if queue.size> $C[:queuesize]
            signal_finder t, 'STOP'
            v 'Queue contains %d files, pausing finder while queue is being processed' % queue.size
            while queue.size> $C[:queuesize]
              sleep $C[:timeout]
            end
            signal_finder t, 'CONT'
          end
        end
        check t.value
      }

      # Closing the queue tells syncers that there will be no more paths
      queue.close
      threads.each &:join
    end
  end
end

class Syncer
  # Returns the next path from the queue. Returns nil if there is none after
  # waiting for timeout seconds, or as soon as queue is closed and empty.
  # (Timeout::timeout isn't used because a path could get lost in a timeout)
  def pop queue
    time= Time.now
    begin
      queue.pop true
    rescue ThreadError
      return if (queue.closed? and queue.empty?) or Time.now- time>= $C[:timeout]
      sleep 0.01
      retry
    end
  end

  def initialize queue, cmd, args, source, dest
    cmdline= [cmd, args, source, dest].flatten
    v "Starting syncer: %s" % [cmdline]

    done= false
    until done
      list= []
      $C[:batchsize].times do |i|
        if path= pop(queue)
          list.push path
        else
          # If queue is closed and empty, there is no need to wait for more paths
          done= (queue.closed? and queue.empty?)
          if list.size> 0
            v 'Finder %s for %s; running syncer with %d out of %d paths' % [done ? 'done' : 'timeout reached', source, list.size, $C[:batchsize]]
          end
          break
        end
      end

      if list.size> 0
        if list.size== $C[:batchsize]
          v 'Finder batch size reached for %s; running syncer with a batch of %d paths' % [source, $C[:batchsize]]
        end
        first_alone do
          read_io, write_io= IO.pipe
          child= fork do
            write_io.close
            STDIN.reopen read_io
            exec *cmdline
          end
          read_io.close
          write_io.write list.join "\0"
          write_io.close
          Process.wait child
          check $?
        end
      end
    end

    #v 'No more finders running and no more paths queued for %s; closing' % [source]
  end
end


#######################################################################
# Run the thing:

v "Config: #{$C}"

sources= Queue.new
$C[:sources].each {|source| sources<< source }
sources.close

threads= []
$C[:finders].times do |i|
  threads<< Thread.new { Finder.new $C[:rsync], $C[:find_options], sources, $C[:destination] }
end
threads.each &:join

exit $C[:runtime][:status]
